name: My workflow
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: echo "Hello, world!"

    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: successful step
              run: |
                  echo "I will fail"
            - name: say goodbye
              run: echo "Bye, world!"
