name: 03- workflow-runner
on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                  echo "I am running on ${{ runner.os }}."
                     echo "I am running on $RUNNER_OS."
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                  echo "I am running on ${{ runner.os }}."
                  echo "I am running on $RUNNER_OS."
