name: 04 - using actions
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: npm ci
              working-directory: 04-using-actions/react-appq

        #checkout code
        #install deps of our react app
        #execute automated tests
