name: 06-contexts
run-name: 06-contexts-${{ inputs.debug }}
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                description: "Enable debug mode"
                type: boolean
                default: false

env:
    MY_WORKFLOW_VAR: "workflow"
    MY_OVERWRITTEN_VAR: "workflow"

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_VAR: "job"
            MY_OVERWRITTEN_VAR: "job"
        steps:
            - name: Display information
              run: |
                  echo "I am running on ${{ runner.os }}."
                    echo "Event name: ${{ github.event_name }}"
                    echo "Ref: ${{ github.ref }}"
                    echo "SHA: ${{ github.sha }}"
                    echo "Actor: ${{ github.actor  }}"
                    echo "Run ID: ${{ github.run_id }}"
                    echo "Run number: ${{ github.run_number }}"

            - name: Retrieve Variable
              run: |
                  echo "The variable is ${{ vars.MY_VAR }}"
            - name: Print Environment Variable
              env:
                  MY_OVERWRITTEN_VAR: "Step"
              run: |
                  echo "The environment variable is ${{ env.MY_WORKFLOW_VAR }}"
                  echo "The job environment variable is ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print Context Variable
              run: |
                  echo "The environment variable is ${{ env.MY_WORKFLOW_VAR }}"
                  echo "The job environment variable is ${{ env.MY_OVERWRITTEN_VAR }}"
