name: 07-expressions
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                description: "Enable debug mode"
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print start-up data"
              if: ${{ inputs.debug }}
              run: |
                  echo "I am running on ${{ runner.os }}."
                  echo "Event name: ${{ github.event_name }}"
                  echo "Ref: ${{ github.ref }}"
                  echo "SHA: ${{ github.sha }}"
                  echo "Actor: ${{ github.actor  }}"
                  echo "Run ID: ${{ github.run_id }}"
                  echo "Run number: ${{ github.run_number }}"
            - name: "[debug] Print when triggered from main"
              if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
              run: |
                  echo "Debug mode is ${{ inputs.debug }}"
            - name: "Greeting"
              run: |
                  echo "Hello, world!"
